addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker-compose build test
  - docker-compose run --rm test
  - docker build .

after_success:
  - bin/deploy "${TRAVIS_TAG:-dev}"
