addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker-compose run --rm test
  - docker-compose run --rm kt clean
  - docker-compose run --rm kt compile -e qa
  - docker-compose run --rm kt compile -e preprod -c mycomponent

after_success:
  - bin/deploy "${TRAVIS_TAG:-dev}"
