version: "2.3"

x-base: &base
  build:
    context: .
    target: build
  volumes:
    - ".:/app"
    - "$HOME/.kube:/root/.kube"
    - "./meta:/opt/meta"
  working_dir: /app

services:
  build:
    <<: *base
    entrypoint:
      - cabal
      - build

  repl:
    <<: *base
    entrypoint:
      - cabal
      - repl

  kt:
    <<: *base
    entrypoint: |
      cabal run kt -- -C example

  sh:
    <<: *base
    entrypoint:
      - sh
