version: "2.3"

x-base: &base
  build:
    context: .
    target: build
  volumes:
    - ".:/go/src/app"
  environment:
    AWS_REGION: ap-southeast-2

services:
  kt:
    build: .
    volumes:
      - "./example:/app"

  sh:
    <<: *base
    command: sh

  test:
    <<: *base
    command: go test
