version: "2.3"

x-base: &base
  build: .
  volumes:
    - ".:/app"
    - "$HOME/.kube:/root/.kube"
  working_dir: /app
  

services:
  shake:
    <<: *base
    entrypoint: 
      - runhaskell
      - Build.hs

  sh:
    <<: *base
    entrypoint: [sh]
    
  kubectl:
    <<: *base
    entrypoint: [kubectl]
