version: "2.3"

x-base: &base
  build:
    context: .
    target: app
  volumes:
    - "./example:/app"
    - ".:/kt"
    - "$HOME/.kube:/root/.kube"
  working_dir: /app
  environment:
    AWS_REGION: ap-southeast-2

services:
  kt:
    <<: *base
    entrypoint:
      - /kt/kt

  sh:
    <<: *base
    entrypoint:
      - bash
