version: "2.3"

x-base: &base
  build:
    context: .
    target: build
  volumes:
    - ".:/app"
    - "$HOME/.kube:/root/.kube"
    - "./meta:/opt/meta"
  working_dir: /app

services:
  cabal:
    <<: *base
    entrypoint:
      - cabal

  sh:
    <<: *base
    entrypoint:
      - sh
