{{- $config := (datasource "config") -}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mycomponentapp
  namespace: default
  labels:
    app: mycomponentapp
    parameter: {{ $config.param }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mycomponentapp
        parameter: {{ $config.param }}
      annotations:
        config/checksum: "{{ crypto.SHA256 (file.Read "templates/initial/00-namespaces.yaml") }}"
    spec:
      containers:
      - name: operator
        imagePullPolicy: Always
        image: nginx
        env:
          - name: "MYENVSPECIFICVAR"
            value: "{{ $config.myenvspecicvar }}"
          - name: "MYOTHERENVSPECIFICVAR"
            value: "{{ $config.my.other.env.specific.variable }}"
