{{- $config := (datasource "config") -}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: operator
        imagePullPolicy: Always
        image: nginx
        env:
          - name: "MYENVSPECIFICVAR"
            value: "{{ $config.myenvspecicvar }}"
