{{- $config := (datasource "config") -}}
---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: my-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: s3read
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
              - "s3:GetObject"
              Resource: "arn:aws:xxxxxx:/non-existent-bucket-{{ $config.myenvspecicvar }}"
